config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :contents do
    resources :comments, only:[:create]
    get 'show', :to => 'contents#show'
  end
  #resources :relationships, only:[:create, :destroy]
  
  #tag機能
  resources :tags
    resources :tag_users do
      member do
        get :move_higher
        get :move_lower
      end
    end
  
  #ログイン機能
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks'
    }
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  #プロフィール用
  resources :users, only: [:edit, :update] do
    collection do
      get 'plofile/edit', :to => 'users#edit'
      put 'plofile', :to => 'users#update' 
    end
  end
  
  #フォロー用
  resources :users do
    resource :relationships, only:[:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'profile', :to => 'users#profile'
  end
  
  #いいね機能
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  #トレンド機能
  get 'trend', :to => 'trends#index'
  
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  
  has_many :tag_contents, dependent: :destroy
  has_many :tags, through: :tag_contents
  
  has_many :likes
  has_many :comments
  
  validates :body, presence: true
  
  def comments_new
    comments.new
  end
  
  def save_tags(tag_list, tag_check)
    tag_list.each do |tag|
      # 受け取った値を小文字に変換して、DBを検索して存在しない場合は
      # find_tag に nil が代入され　nil となるのでタグの作成が始まる
      find_tag = Tag.find_by(tag_name: tag.downcase)
      if find_tag == nil
        begin
          # create メソッドでタグの作成
          # create! としているのは、保存が成功しても失敗してもオブジェクト
          # を返してしまうため、例外を発生させたい
          puts "=========================="
          puts self.id
          puts tag
          puts find_tag
          puts "=========================="
          Tag.create(tag_name: tag)
        # 例外が発生すると rescue 内の処理が走り nil となるので
        # 値は保存されないで次の処理に進む
        rescue
          nil
        end
      else
        
      end
      #tag_list.eachの最後にcreateを実行
      #@tagに先程作成したタグor既存タグのデータを抽出
      @tag = Tag.find_by(tag_name: tag)
      TagContent.create!(content_id: self.id, tag_id: @tag.id)
      #チェックボックスがオンの時　tag_userを保存
      #binding.pry
      if tag_check.blank?
        #tag_check空なので通過
      else  #tag_checkオンでblankじゃないことを確認
        #ユーザーの持っているお気に入りの一番大きい値を確認
        last_position = TagUser.select(:position).where(user_id: user.id) .order(position: :desc)&.first
        if last_position.blank?
          #初めてのお気に入りなので
          TagUser.create!(user_id: user.id, tag_id: @tag.id, position: 1)
        else
        #last_positionを整数にして保存
        last_p = last_position[:position].to_i
        #TagUserのテーブルをクリエイトする
        TagUser.create!(user_id: user.id, tag_id: @tag.id, position: last_p + 1)
        end
      end
    end
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  def index
    #ユーザーが持ってるコンテンツのみ(current_user.contentsしてるから)
    #@contents = current_user.contents.order(created_at: :desc)
    #コンテンツテーブルから全部のデータを引っ張ってくる
    #@contents = Content.all
    #最終目標：current_userとtarget_idのユーザーのコンテンツを降順で表示
    @contents = Content.where(user_id: [current_user.id, *current_user.following_ids]).order(created_at: :desc)
    #@content = current_user.content.new #ビューのform_withのmodelに使う
  end
  
  def show
    @content = Content.find(params[:content_id])
    @comments = @content.comments
    @comment = @comments.new
    @tags = @content.tags
  end

  # GET /contents/new
  def new
    @content = current_user.contents.new
  end

  # GET /contents/1/edit
  def edit
    
  end

  # POST /contents
  def create
    @content = current_user.contents.new(content_params)
    @content.user_id = current_user.id
    tag_list = tag_params[:tag_name].split(nil)
    tag_check = params.require(:content).permit(:tag_check).values
    
    if @content.save
      #タグの保存
      @content.save_tags(tag_list, tag_check)
      #トップへリダイレクト
      redirect_to action: :index, flash:{ success: 'つぶやきに成功しました'}
    else
      
      render :new
    end
  end

  # PATCH/PUT /contents/1
  def update
    tag_list = tag_params[:tag_name].split(nil)
    if @content.update(content_params)
      @content.save_tags(tag_list)
      redirect_to action: :index, flash:{success: 'つぶやきを更新しました'}
    else
      
      render :edit
    end
  end

  # DELETE /contents/1
  def destroy
    @content.destroy
    redirect_to action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #元は@goal = Content.find(params[:id])だった　current_userのデータのみshow～destroyで使うってこと？
    def set_content
      @content = current_user.contents.find_by(id: params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def content_params
      params.require(:content).permit(:user_id, :body, tag_ids:[],)
    end
    def tag_params
      params.require(:content).permit(:tag_name)
    end
    
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">
      <h6><%= link_to content.user.name, user_profile_path(content.user.id) %></h6>
    <p class="card-text"><%= content.body %></p>
    <%= content.user.email %> 作成日：<%= content.created_at %>

    <hr>
    <div id="likes_buttons_<%= content.id %>">
      <%= render partial: 'likes/like', locals: {content: content} %>
    </div>
    <!--　indexからのアクションのみ、内容確認を表示させたい　-->
    <% if action_name == "index" %>
        <%= link_to '内容を確認', content_show_path(content), class: "btn btn-outline-primary" %>
    <% end %>
    

  </div>
</div>
<!--.to_s(:datetime_jp)-->

app/views/contents/_form.html.erb
<%= form_with(model: @content, local: true) do |form| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= @content.user.name %>
  </div>

  <div class="field">
    <%= form.text_area :body %>
  </div>
  <div class="field">
    <%= form.text_field :tag_name %>
  </div>
  <div class="field">
    <%= form.check_box :tag_check, {} , 1, nil  %>タグをお気に入りに追加
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="editbody">
<h3>Editing Content</h3>

<%= render 'form', content: @content %>

<%= link_to '戻る', content_show_path(@content) %> |
<%= link_to '一覧に戻る', contents_path %>
</div>

app/views/contents/index.html.erb
<h3>Contents</h3>
<%= link_to 'New Content', new_content_path %>
<%= render @contents %>

app/views/contents/new.html.erb
<div class="editbody">
<h3>New Content</h3>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>
</div>

app/views/contents/show.html.erb
<%= render partial: @content %>
<hr>

<% @tags.each do |tag| %>
  <%= tag.tag_name %>
<% end %>
<br>
<hr>
<% if @content.user_id == current_user.id %>
    <%= link_to 'Edit', edit_content_path(@content), class: "btn btn-outline-primary" %>
    <%= link_to 'Destroy', @content, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
<% else %>
    <%= link_to '一覧に戻る', contents_path %>
<% end %>
    
    <%= render 'comments/comment' %>
</p>
<!--このページでやりたいこと<br>
1．本記事（返信元）を表示↑<br>
2．返信ボタンを用意<br>
3．返信で書かれた記事を表示<br>
返信記事の抽出をcontrollerにdef showで記述、<br>
本記事の下にeach　doで表示 -->