config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :contents do
    resources :comments, only:[:create]
    get 'show', :to => 'contents#show'
  end
  #resources :relationships, only:[:create, :destroy]
  
  #tag機能
  resources :tags
    resources :tag_users do
      member do
        get :move_higher
        get :move_lower
      end
    end
  
  #ログイン機能
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks'
    }
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  #プロフィール用
  resources :users, only: [:edit, :update] do
    collection do
      get 'plofile/edit', :to => 'users#edit'
      put 'plofile', :to => 'users#update' 
    end
  end
  
  #フォロー用
  resources :users do
    resource :relationships, only:[:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'profile', :to => 'users#profile'
  end
  
  #いいね機能
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  #トレンド機能
  get 'trend', :to => 'trends#index'
  
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :content
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :content_params
    
    def create
        Like.create(user_id: current_user.id, content_id: params[:id])
    end
    
    def destroy
        Like.find_by(user_id: current_user.id, content_id: params[:id]).destroy
    end
    
    private
    def content_params
       @content = Content.find(params[:id]) 
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
    <% if current_user.like_by?(content.id) %>
    <td><%= link_to 'LIKEをはずす', destroy_like_path(content), method: :DELETE, remote: true %> <%= content.likes.count %></td>
     <% else %>
    <td><%= link_to 'いいね', create_like_path(content), method: :POST, remote: true %> <%= content.likes.count %></td>
 <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @content.id %>').html("<%= j(render partial: 'likes/like', locals: {content: @content}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @content.id %>').html("<%= j(render partial: 'likes/like', locals: {content: @content}) %>");