config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :contents do
    resources :comments, only:[:create]
    get 'show', :to => 'contents#show'
  end
  #resources :relationships, only:[:create, :destroy]
  
  #tag機能
  resources :tags
    resources :tag_users do
      member do
        get :move_higher
        get :move_lower
      end
    end
  
  #ログイン機能
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks'
    }
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  #プロフィール用
  resources :users, only: [:edit, :update] do
    collection do
      get 'plofile/edit', :to => 'users#edit'
      put 'plofile', :to => 'users#update' 
    end
  end
  
  #フォロー用
  resources :users do
    resource :relationships, only:[:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'profile', :to => 'users#profile'
  end
  
  #いいね機能
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  #トレンド機能
  get 'trend', :to => 'trends#index'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  
  #Profile画像の設定
  mount_uploader :avatar, AvatarUploader
  
  has_many :contents
  has_many :comments
  has_many :likes
  has_many :tag_users
  has_many :tags, through: :tag_users
  
  #follow(rerationship)用の記述
  has_many :relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "target_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :target
  has_many :followers, through: :reverse_of_relationships, source: :follow
  
  #フォロー用のメソッド
  def follow(user_id)
    relationships.find_or_create_by(target_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(target_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  #いいね機能のメソッド
  def like_by?(content_id)
    likes.where(content_id: content_id).exists?
  end
  
  

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(
       :sign_up, keys: [:name, :email, :password, :password_confirmation ])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(
       :account_update, keys: [:name, :profile, :email, :password, :password_confirmation])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  def after_sign_in_path_for(user)
   contents_path
  end
  
  def after_sigin_out_path_for(user)
   root_path
  end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(
       :sign_in, keys: [:email, :password, :password_confirmation])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def edit
    set_user
  end
  
  def update
    set_user
    @user.update_without_password(user_params)
    redirect_to root_path
  end
  
  def show
    set_user
  end
  
  def profile
    @user = User.find_by(id: params[:user_id])
  end
  
  private
    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:name, :email, :profile, :avatar, :password, :password_confirmation)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <h3 class="mt-3 mb-3">プロフィールの編集</h3>
            <hr>
            <%= form_with model: current_user, local: true, method: :put do |f| %>
        <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :name, "名前", class: "text-md-left tsublog-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userName', '.editUserName', '.userNameEditLabel');" class="userNameEditLabel user-edit-label">
              編集
            </span>
          </div>
          <div class="collapse show userName">
            <h3 class="tsublog-edit-user-info-value"><%= @user.name %></h3>
          </div>
          <div class="collapse editUserName">
            <%=
              f.text_field :name,
              class: "form-control #{"is-invalid" if @user.errors.messages[:name].present? } ",
              value: @user.name,
              autofocus: "true",
              required: "",
              autocomplete: "name",
              placeholder: "名前を入力"
            %>

            <%= f.submit "保存", class: "btn tsublog-submit-button mt-3 w-25" %>

            <% if @user.errors.messages[:name].present? %>
            <span class="invalid-feedback" role="alert">
              <strong>名前を入力してください</strong>
            </span>
            <% end %>
          </div>
        </div>
        
          <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :avatar, "ユーザー画像", class: "text-md-left tsublog-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userAvatar', '.editUserAvatar', '.userAvatarEditLabel');" class="userAvatarEditLabel user-edit-label">
              編集
            </span>
          </div>
          <div class="collapse show userAvatar">
            <h3 class="tsublog-edit-user-info-value">
              <% if @user.avatar? %>
                <%= image_tag @user.avatar.url, class: 'rounded-circle mr15', width: '40', height: '40' %>
              <% else %>
              <% end %></h3>
          </div>
          <div class="collapse editUserAvatar">
            <%=
              f.file_field :avatar, onchange: 'previewImage()', class: 'form-control'
            %>
            <%= f.hidden_field :avatar_cache %>
            <%= image_tag @user.avatar.url, class: 'rounded-circle mt-3', id: 'preview', size: '100x100' %>
            <%= f.submit "保存", class: "btn tsublog-submit-button mt-3 w-25" %>

            <% if @user.errors.messages[:avatar].present? %>
            <span class="invalid-feedback" role="alert">
              <strong>画像を選択してください</strong>
            </span>
            <% end %>
          </div>
        </div>
        <hr>
        
        <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :profile, "プロフィール", class: "text-md-left tsublog-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userProfile', '.editUserProfile', '.userProfileEditLabel');" class="userProfileEditLabel user-edit-label">
              編集
            </span>
          </div>
          <div class="collapse show userProfile">
            <h3 class="tsublog-edit-user-info-value"><%= @user.profile %></h3>
          </div>
          <div class="collapse editUserProfile">
            <%=
              f.text_area :profile,
              class: "form-control #{"is-invalid" if @user.errors.messages[:profile].present? }",
              autofocus: "true",
              required: "",
              value: @user.profile,
              autocomplete: "profile",
              placeholder: "プロフィールを入力"
            %>

            <%= f.submit "保存", class: "btn tsublog-submit-button mt-3 w-25" %>

            <% if @user.errors.messages[:profile].present? %>
            <span class="invalid-feedback" role="alert">
              <strong>プロフィールを入力してください</strong>
            </span>
            <% end %>
          </div>
        </div>
        
        <hr>
        
        <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :email, "メールアドレス", class: "text-md-left tsublog-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userMail', '.editUserMail', '.userMailEditLabel');" class="userMailEditLabel user-edit-label">
              編集
            </span>
          </div>
          <div class="collapse show userMail">
            <h3 class="tsublog-edit-user-info-value"><%= @user.email %></h3>
          </div>
          <div class="collapse editUserMail">
            <%=
              f.email_field :email,
              class: "form-control #{"is-invalid" if @user.errors.messages[:email].present? }",
              autofocus: "true",
              required: "",
              value: @user.email,
              autocomplete: "email",
              placeholder: "メールアドレスを入力"
            %>

            <%= f.submit "保存", class: "btn tsublog-submit-button mt-3 w-25" %>

            <% if @user.errors.messages[:email].present? %>
            <span class="invalid-feedback" role="alert">
              <strong>メールアドレスを入力してください</strong>
            </span>
            <% end %>
          </div>
        </div>
            <% end %>
            
<script type="text/javascript">
    let switchEditUserInfo = (textClass, inputClass, labelClass) => {
        if ($(textClass).css('display') == 'block') {
            $(labelClass).text("キャンセル");
            $(textClass).collapse('hide');
            $(inputClass).collapse('show');
        } else {
            $(labelClass).text("編集");
            $(textClass).collapse('show');
            $(inputClass).collapse('hide');
        }
    }
    function previewImage() {
    const target = this.event.target;
    const file = target.files[0];
    const reader  = new FileReader();
    reader.onloadend = function () {
        const preview = document.querySelector("#preview")
        if(preview) {
            preview.src = reader.result;
        }
    }
    if (file) {
        reader.readAsDataURL(file);
    }
  }
</script>
        
        </div>
    </div>
</div>

app/views/users/profile.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
<h3>Profile</h3>

<hr>
<br>

<h3>ユーザー名</h3>
<%= @user.name %>
<hr>
<% if @user.avatar? %>
<%= image_tag @user.avatar.url, class: 'rounded-circle mr15', width: '40', height: '40' %>
<% end %>
<hr>
<h3>プロフィール</h3>
<%= @user.profile %>
<hr>
<h3>フレンド</h3>
<% if @user.id  == current_user.id %>
<%= link_to "フォロー一覧", user_followings_path %>
<%= link_to "フォロワー一覧", user_followers_path %>
<hr>
<%= link_to "編集する", plofile_edit_users_path %>
<% else %>
<%= render 'relationships/follow_form', user: @user %>
<% end %>
<hr>


        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
<h3>Profile</h3>

<hr>
<br>

<h3>ユーザー名</h3>
<%= @user.name %>
<hr>
<h3>プロフィール</h3>
<%= @user.profile %>
<hr>
<h3>フレンド</h3>
<%= link_to "フォロー一覧", user_followings_path %>
<%= link_to "フォロワー一覧", user_followers_path %>
<hr>
<%= link_to "編集する", mypage_edit_users_path %>

        </div>
    </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>