config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :contents do
    resources :comments, only:[:create]
    get 'show', :to => 'contents#show'
  end
  #resources :relationships, only:[:create, :destroy]
  
  #tag機能
  resources :tags
    resources :tag_users do
      member do
        get :move_higher
        get :move_lower
      end
    end
  
  #ログイン機能
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks'
    }
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  #プロフィール用
  resources :users, only: [:edit, :update] do
    collection do
      get 'plofile/edit', :to => 'users#edit'
      put 'plofile', :to => 'users#update' 
    end
  end
  
  #フォロー用
  resources :users do
    resource :relationships, only:[:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'profile', :to => 'users#profile'
  end
  
  #いいね機能
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  #トレンド機能
  get 'trend', :to => 'trends#index'
  
end

app/models/tag_user.rb
class TagUser < ApplicationRecord
    belongs_to :user, class_name: 'User'
    belongs_to :tag, class_name: 'Tag'
    
    validates :user_id, :uniqueness => { :scope => :tag_id }

    #並び替え機能
    acts_as_list
end

app/controllers/tag_users_controller.rb
class TagUsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_tags
    before_action :set_tag_users, only: [:show, :edit, :update, :destroy]
    
    def index
        #ユーザーの持っているtag_user(中間)データを抽出する
       @tag_users = current_user.tag_users.order(:position)
       #@tags = current_user.tags
    end
    def move_higher
        TagUser.find(params[:id]).move_higher #move_higherメソッドでpositionを上に
        redirect_to action: :index
    end
    def move_lower
        TagUser.find(params[:id]).move_lower #move_lowerメソッドでpositionを下に
        redirect_to action: :index
    end
    def destroy
        
        @tag_users.destroy
        redirect_to action: :index
    end

  
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag_users
        @tag_users = current_user.tag_users.find_by(id: params[:id])
    end
    def set_tags
        @tag =current_user.tags.find_by(id: params[:id]) 
    end
    
    # Only allow a trusted parameter "white list" through.
    def tag_params
        params.require(:tag).permit(:tag_name, :user_id, :tag_id)
    end
    def tag_user_params
        params.require(:tag_user).permit(:tag_id, :user_id, :position)
    end
    
end

app/helpers/tag_users_helper.rb
module TagUsersHelper
end

app/views/tag_users/index.html.erb
<h3>お気に入りタグ</h3>
<br>
<!--　formはlink_to+modalで下記にJS記述してmodalウィンドウで対応にしたい -->
 <%= link_to new_tag_path, title: "New", class: "btn p-0 text-dark" do %>
    <i class="fas fa-plus align-middle pr-1"></i><span class="align-middle">新しいタグを作成</span>
  <% end %>
<hr>
<div id='task-list'>
<table>
  <thead>
    <tr>
      <th>タグ名</th>
      <th>順番</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tag_users.each do |t| %>
      <tr>
        <td><%= t.tag.tag_name %></td>
        <td><%= t.position %></td>
        <td><%= link_to "削除", t, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
        <td><%= link_to "↑", move_higher_tag_user_path(t) %></td>
        <td><%= link_to "↓", move_lower_tag_user_path(t) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<script type="text/javascript">

</script>